<?php

namespace AppBundle\Repository;

/**
 * AProposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AProposRepository extends \Doctrine\ORM\EntityRepository
{
}
