<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function displayEnabled()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.enabled = 1');
        return $qb->getQuery()->getResult();
    }
    
}
