<?php

namespace AppBundle\Repository;

/**
 * PressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressRepository extends \Doctrine\ORM\EntityRepository
{
}
