<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\From;
use AppBundle\Entity\Article;



/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{

    public function squeezeDropdown()
    {

        $qb = $this->createQueryBuilder('s')
        ->where('s.id < 3')
        ->orWhere('s.id <= 5');
        return $qb->getQuery()->getResult();

    }

    public function displayAccueil()
    {
        $qb = $this->createQueryBuilder('s')
        ->where('s.enabled = 1');
        return $qb->getQuery()->getResult();
    }

    public function displaySection()
    {
        $qb = $this->createQueryBuilder('s')
        ->where('s.enabled = 1');
        return $qb->getQuery()->getResult();
    }

    
}
