<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\From;


/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{

    public function squeezeDropdown()
    {

        $qb = $this->createQueryBuilder('s')
        ->where('s.id')
        ->orWhere('s.id > 5');
        return $qb->getQuery()->getResult();

    }
    
}
